# Components
fluidRow(
    column(width = 4,
           numericInput(inputId = "batchSize",
                        label = "Batch Size (Gal):",
                        value = 5.5),
           numericInput(inputId = "boilTime",
                        label = "Boil Time (Min):",
                        value = 60),
           numericInput(inputId = "evap",
                        label = "Evaporation (%/hr)",
                        value = 5),
           numericInput(inputId = "shrink",
                        label = "Shrinkage From Cooling (%)",
                        value = 4),
           numericInput(inputId = "sysEfficiency",
                        label = "Brew House Efficiency (%)",
                        value = 70),
           numericInput(inputId = "scaleRecipe",
                        label = "Scale Current Recipe (%)",
                        value = 100)
    ),
    column(width = 4, offset = 4,
           numericInput(inputId = "weightMashTun",
                        label = "Weight of Mash Tun (lbs):",
                        value = 7.5),
           numericInput(inputId = "thermalMassMashTun",
                        label = "Thermal Mash of Mash Tun (btu/(lb*F)):",
                        value = 0.38),
           numericInput(inputId = "kettleDeadSpace",
                        label = "Boil Kettle Dead Space (Gal):",
                        value = 0.5),
           numericInput(inputId = "lauterTunDeadSpace",
                        label = "Lauter Tun Dead Space (Gal):",
                        value = 0.5),
           numericInput(inputId = "mashTunDeadSpace",
                        label = "Mash Tun Dead Space (Gal):",
                        value = 0),
           numericInput(inputId = "fermentationTankLoss",
                        label = "Fermentation Tank Loss (Gal):",
                        value = 0)
    )
),
h4("System Specific Information"),
h4("Fermentable Ingredients"),
selectInput(inputId = "Hops",label = "Select Hops:",choices = list("Saaz")),
h4("Yeast Strain Calculated Information"),
selectInput(inputId = "Grains",label = "Select Grains:",choices = list("Caramel")),
h4("Hop Additions"),
selectInput(inputId = "Hops",label = "Select Hops:",choices = list("Saaz")),
h4("Mash Parameters"),
selectInput(inputId = "Grains",label = "Select Grains:",choices = list("Caramel")),
h4("Water Profile"),
selectInput(inputId = "Hops",label = "Select Hops:",choices = list("Saaz")),
h4("Fermentation Notes"),
selectInput(inputId = "Grains",label = "Select Grains:",choices = list("Caramel"))

